name: Redirect

on:
  push:
    branches:
      - master

jobs:
  redirect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/redirect
        with:
          port: 8080
